/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/cono.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_iceCream.geometry}
        material={materials.purpleLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_iceCream_1.geometry}
        material={materials.brownLight}
      />
    </group>
  );
}

useGLTF.preload("/cono.gltf");